name: Build rules
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm insall
      - name: Build with Next.js
        run: npm run build
